"""
Domain Models — AI-SOC Architecture & ActionSpec Contract

Pydantic v2 schemas for the AI-SOC data layer, incorporating:
  - Canonical incident / event schema with tenant isolation
  - ActionSpec contract (ActionProposal, PolicyDecision, ExecutionResult)
  - Traceable evidence bundles with provenance and confidence
  - Cryptographic tamper-evident audit decision events
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class SeverityLevel(str, Enum):
    """CVSS-aligned severity taxonomy."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class IncidentStatus(str, Enum):
    """Full incident lifecycle states."""
    NEW = "new"
    TRIAGING = "triaging"
    INVESTIGATING = "investigating"
    CONTAINED = "contained"
    ERADICATED = "eradicated"
    RECOVERING = "recovering"
    CLOSED = "closed"
    FALSE_POSITIVE = "false_positive"


class AutonomyTier(str, Enum):
    """Action risk classification tiers."""
    TIER_0_OBSERVE = "tier_0_observe"
    TIER_1_ADMINISTRATIVE = "tier_1_administrative"
    TIER_2_BOUNDED_CONTAINMENT = "tier_2_bounded_containment"
    TIER_3_DISRUPTIVE = "tier_3_disruptive"
    TIER_4_DESTRUCTIVE = "tier_4_destructive"


class PolicyDecisionType(str, Enum):
    """Deterministic policy engine decision."""
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    ALLOW = "ALLOW"


class ActionExecutionStatus(str, Enum):
    """Lifecycle status of an approved or automated action."""
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    EXECUTING = "executing"
    SUCCESS = "success"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


# ---------------------------------------------------------------------------
# ActionSpec Contract Schemas
# ---------------------------------------------------------------------------


class ActionProposal(BaseModel):
    """Structured proposal generated by an AI agent; strictly requires policy authorization."""
    id: str = Field(..., description="Unique action proposal ID")
    tenant_id: str = Field(..., description="Tenant isolation boundary")
    incident_id: str = Field(..., description="Target incident ID")
    action_type: str = Field(..., description="e.g. firewall_block, isolate_endpoint")
    target_type: str = Field(..., description="e.g. ip, host, user")
    target_id: str = Field(..., description="e.g. 185.220.101.47")
    evidence_refs: List[str] = Field(default_factory=list, description="IDs of supporting evidence items")
    rationale: str = Field(..., description="Grounded explanation with citations")
    risk_tier: AutonomyTier = Field(..., description="Tier 0 through Tier 4")
    expected_effect: str = Field(..., description="Operational effect")
    blast_radius: str = Field(..., description="Scope of impact")
    ttl_seconds: int = Field(default=3600, description="Auto-rollback duration in seconds")
    preconditions: List[str] = Field(default_factory=list, description="Pre-execution checks")
    postconditions: List[str] = Field(default_factory=list, description="Verification criteria")
    rollback_action: str = Field(..., description="Compensating rollback command")
    requested_by_agent: str = Field(..., description="Agent / node identifier")
    model_version: str = Field(..., description="e.g. claude-3-5-sonnet")
    prompt_version: str = Field(..., description="Prompt template version")


class PolicyDecision(BaseModel):
    """Deterministic policy engine evaluation output."""
    decision: PolicyDecisionType
    policy_version: str = Field(..., description="Version of the evaluated policy rule")
    reason_codes: List[str] = Field(default_factory=list, description="Policy rule match codes")
    required_approvers: List[str] = Field(default_factory=list, description="Roles required for approval")
    decided_at: datetime = Field(default_factory=datetime.utcnow)


class ExecutionResult(BaseModel):
    """Result emitted by the Action Broker after policy authorization."""
    executor_id: str = Field(..., description="Action broker executor identifier")
    idempotency_key: str = Field(..., description="Unique key preventing duplicate execution")
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    status: ActionExecutionStatus = Field(default=ActionExecutionStatus.PENDING)
    verification_evidence: List[str] = Field(default_factory=list)
    rollback_status: Optional[str] = None


class EvidenceItem(BaseModel):
    """Authoritative evidence record with provenance and source confidence."""
    id: str = Field(..., description="Evidence item identifier")
    source: str = Field(..., description="e.g. Wazuh, Splunk ES, VirusTotal")
    source_type: str = Field(..., description="wazuh | splunk | threat_intel | edr | network")
    timestamp: datetime
    confidence: float = Field(..., ge=0.0, le=1.0)
    provenance: str = Field(..., description="Audit pointer to raw sensor or API query")
    summary: str = Field(..., description="Extracted factual summary")
    raw_payload: Optional[Dict[str, Any]] = None


class AuditEvent(BaseModel):
    """Tamper-evident decision and action log entry."""
    id: str
    timestamp: datetime
    actor: str = Field(..., description="Agent, PolicyEngine, or Operator identity")
    event_type: str
    details: str
    signature_hash: str = Field(..., description="Cryptographic SHA-256 integrity hash")


class AttckTechnique(BaseModel):
    """MITRE ATT&CK candidate mapping with confidence calibration."""
    id: str = Field(..., description="e.g. T1110.001")
    name: str = Field(..., description="e.g. Password Guessing")
    tactic: str = Field(..., description="e.g. Credential Access")
    confidence: float = Field(..., ge=0.0, le=1.0)


# ---------------------------------------------------------------------------
# Canonical Incident Schema
# ---------------------------------------------------------------------------


class Incident(BaseModel):
    """Canonical incident schema with complete evidence and action traceability."""
    id: str = Field(..., description="Unique incident identifier")
    tenant_id: str = Field(default="default_tenant", description="Tenant isolation key")
    timestamp: datetime = Field(..., description="UTC creation timestamp")
    source: str = Field(..., description="Originating sensor / data source")
    event_type: str = Field(..., description="Normalized event category")
    severity: SeverityLevel
    status: IncidentStatus
    description: Optional[str] = Field(None, description="Human-readable incident summary")
    affected_host: Optional[str] = Field(None, description="Target hostname or IP")
    attck_technique: Optional[AttckTechnique] = None
    agent_summary: Optional[str] = None
    agent_recommendation: Optional[str] = None
    evidence_bundle: List[EvidenceItem] = Field(default_factory=list)
    proposed_action: Optional[ActionProposal] = None
    policy_decision: Optional[PolicyDecision] = None
    execution_result: Optional[ExecutionResult] = None
    audit_trail: List[AuditEvent] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Request & Response Wrappers
# ---------------------------------------------------------------------------


class ActionApprovalRequest(BaseModel):
    """Request payload for an analyst approving/denying an ActionProposal."""
    decision: str = Field(..., description="'approve' or 'deny'")
    operator_notes: Optional[str] = None
    override_ttl_seconds: Optional[int] = None


class HealthResponse(BaseModel):
    status: str
    timestamp: datetime
    version: str
    message: str


class AlertsResponse(BaseModel):
    total: int
    alerts: List[Incident]
